"""app users with reader and admin roles

Revision ID: 1bad292b1416
Revises: 8d0c60b45f97
Create Date: 2026-08-28 09:48:58.736895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bad292b1416'
down_revision: Union[str, Sequence[str], None] = '8d0c60b45f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('borant_sub', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('READER', 'ADMIN', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_borant_sub'), ['borant_sub'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_email'))
        batch_op.drop_index(batch_op.f('ix_app_user_borant_sub'))

    op.drop_table('app_user')
    # ### end Alembic commands ###
