"""initial schema

Revision ID: 443821952e25
Revises: 
Create Date: 2026-08-27 17:48:20.320402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443821952e25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'provider')
    )
    with op.batch_alter_table('budget_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_ledger_day'), ['day'], unique=False)

    op.create_table('match_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('anatomy', sa.JSON(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('text_profile', sa.JSON(), nullable=True),
    sa.Column('scoring_config_version', sa.String(length=32), nullable=True),
    sa.Column('refused_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('hints', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('API', 'GUIDELINES', name='sourcekind'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openalex_id', sa.String(length=64), nullable=True),
    sa.Column('issn_l', sa.String(length=16), nullable=True),
    sa.Column('issns', sa.JSON(), nullable=True),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('host_organization_name', sa.String(length=512), nullable=True),
    sa.Column('homepage_url', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('venue_type', sa.String(length=64), nullable=True),
    sa.Column('is_oa', sa.Boolean(), nullable=True),
    sa.Column('is_in_doaj', sa.Boolean(), nullable=True),
    sa.Column('apc_usd', sa.Integer(), nullable=True),
    sa.Column('apc_prices', sa.JSON(), nullable=True),
    sa.Column('oa_flip_year', sa.Integer(), nullable=True),
    sa.Column('oa_model', sa.Enum('FULL_OA', 'HYBRID', 'OA_OUTSIDE_DOAJ', 'CLOSED_OR_UNKNOWN', name='oamodel'), nullable=True),
    sa.Column('is_core', sa.Boolean(), nullable=True),
    sa.Column('works_count', sa.Integer(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('two_yr_mean_citedness', sa.Float(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('topics_coverage', sa.Float(), nullable=True),
    sa.Column('licenses', sa.JSON(), nullable=True),
    sa.Column('review_process', sa.JSON(), nullable=True),
    sa.Column('publication_time_weeks', sa.Integer(), nullable=True),
    sa.Column('has_waiver', sa.Boolean(), nullable=True),
    sa.Column('doaj_apc', sa.JSON(), nullable=True),
    sa.Column('anvur_class', sa.String(length=64), nullable=True),
    sa.Column('indexed_in', sa.JSON(), nullable=True),
    sa.Column('predatory_risk', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venue_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_venue_issn_l'), ['issn_l'], unique=True)
        batch_op.create_index(batch_op.f('ix_venue_openalex_id'), ['openalex_id'], unique=False)

    op.create_table('article_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('word_limit_scope', sa.Text(), nullable=True),
    sa.Column('abstract_limit', sa.Integer(), nullable=True),
    sa.Column('refs_limit', sa.Integer(), nullable=True),
    sa.Column('figures_limit', sa.Integer(), nullable=True),
    sa.Column('unsolicited', sa.Boolean(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_type_venue_id'), ['venue_id'], unique=False)

    op.create_table('field_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'field_name')
    )
    with op.batch_alter_table('field_verification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_verification_venue_id'), ['venue_id'], unique=False)

    op.create_table('match_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('score_topic', sa.Float(), nullable=False),
    sa.Column('score_subfield', sa.Float(), nullable=False),
    sa.Column('score_field', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('venue_snapshot', sa.JSON(), nullable=True),
    sa.Column('excluded_by', sa.JSON(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['match_run.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_result_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_result_venue_id'), ['venue_id'], unique=False)

    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proposalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_status'), ['status'], unique=False)

    op.create_table('venue_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_string', sa.String(length=512), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_string', 'source_system')
    )
    with op.batch_alter_table('venue_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venue_alias_alias_string'), ['alias_string'], unique=False)
        batch_op.create_index(batch_op.f('ix_venue_alias_venue_id'), ['venue_id'], unique=False)

    op.create_table('criterion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('MERIT', 'LOGISTICS', name='criterionkind'), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['match_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('criterion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criterion_result_id'), ['result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('criterion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criterion_result_id'))

    op.drop_table('criterion')
    with op.batch_alter_table('venue_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_alias_venue_id'))
        batch_op.drop_index(batch_op.f('ix_venue_alias_alias_string'))

    op.drop_table('venue_alias')
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_status'))

    op.drop_table('proposal')
    with op.batch_alter_table('match_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_result_venue_id'))
        batch_op.drop_index(batch_op.f('ix_match_result_run_id'))

    op.drop_table('match_result')
    with op.batch_alter_table('field_verification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_verification_venue_id'))

    op.drop_table('field_verification')
    with op.batch_alter_table('article_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_type_venue_id'))

    op.drop_table('article_type')
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_openalex_id'))
        batch_op.drop_index(batch_op.f('ix_venue_issn_l'))
        batch_op.drop_index(batch_op.f('ix_venue_display_name'))

    op.drop_table('venue')
    op.drop_table('source')
    op.drop_table('match_run')
    with op.batch_alter_table('budget_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_ledger_day'))

    op.drop_table('budget_ledger')
    # ### end Alembic commands ###
