"""rank is a position, not a rank

The autogenerated version of this migration was a DROP plus an ADD, which is what
Alembic infers when a column changes name: it cannot tell a rename from a
deletion and an unrelated creation. Applying it would have thrown away every
recorded position. Written by hand as an actual rename.

The name matters beyond tidiness. A rank implies a fixed set ordered by a stable
criterion; here the score is computed against one paper and the set is whatever
stage 2 managed to reach that day, so "#447 of 3810" is an artefact of how many
candidates were fetched. See SPEC.md §0.

Revision ID: 8d0c60b45f97
Revises: 443821952e25
"""

from __future__ import annotations

from alembic import op

revision = "8d0c60b45f97"
down_revision = "443821952e25"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # batch mode because SQLite cannot ALTER a column: it rebuilds the table.
    with op.batch_alter_table("match_result") as batch:
        batch.alter_column("rank", new_column_name="position")


def downgrade() -> None:
    with op.batch_alter_table("match_result") as batch:
        batch.alter_column("position", new_column_name="rank")
